import pytest
from unittest.mock import patch
from llm_service.quiz_generator import generate_quiz

# A valid mock response from the LLM for MCQ
mock_mcq_response = {
    "question": "Which of the following is a mutable data type in Python?",
    "type": "mcq",
    "difficulty": "easy",
    "skill_tag": "Python",
    "options": ["tuple", "list", "int", "str"],
    "correct_answer": "list"
}

# A valid mock response from the LLM for Essay
mock_essay_response = {
    "question": "Explain the difference between deep copy and shallow copy in Python.",
    "type": "text",
    "difficulty": "medium",
    "skill_tag": "Python",
    "options": None
}

@patch("llm_service.quiz_generator.call_llm")
def test_generate_quiz_schema(mock_call_llm):
    """
    Test the structure generated by generate_quiz.
    We mock call_llm to simulate LLM returning our mock responses.
    """
    # For n_per_skill=2, we get 1 MCQ, 1 Essay.
    # MagicMock will return MCQ on first call, Essay on second call.
    mock_call_llm.side_effect = [mock_mcq_response, mock_essay_response]
    
    quiz = generate_quiz(["Python"], "Data Analyst", n_per_skill=2)
    
    assert "questions" in quiz
    assert len(quiz["questions"]) == 2
    
    q1 = quiz["questions"][0]
    q2 = quiz["questions"][1]
    
    assert q1["type"] == "mcq"
    assert q1["skill_tag"] == "Python"
    assert len(q1["options"]) == 4
    
    assert q2["type"] == "text"
    assert q2["skill_tag"] == "Python"
    assert q2["options"] is None

@pytest.mark.integration
def test_quiz_generator_integration():
    """
    Live API test for the Quiz generator across multiple skills.
    Use n_per_skill=1 here to limit cost and time.
    """
    # 1 skill * 1 per skill -> 1 MCQ (round(1 * 0.6) = 1 MCQ, 0 Essay)
    quiz = generate_quiz(["SQL"], "Data Analyst", n_per_skill=1)
    
    assert "questions" in quiz
    assert isinstance(quiz["questions"], list)
    assert len(quiz["questions"]) == 1
    
    q1 = quiz["questions"][0]
    assert "question" in q1
    assert "type" in q1
    assert q1["type"] == "mcq"
    assert q1["skill_tag"] == "SQL"
