# -*- coding: utf-8 -*-
"""depi26_CV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h71_Lm4sr1hni747klDQ1BUskPGrA2w3
"""

import pandas as pd
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier
import kagglehub
#adabosting
from sklearn.ensemble import AdaBoostClassifier
from xgboost import XGBClassifier
from imblearn.ensemble import BalancedRandomForestClassifier

path = kagglehub.dataset_download("kshitizregmi/jobs-and-job-description")
df = pd.read_csv(f"{path}/job_title_des.csv")

df.head()

df.drop("Unnamed: 0",axis=1,inplace=True)

Min_Samples = 30
job_counts = df["Job Title"].value_counts()
valid_jobs = job_counts[job_counts >= Min_Samples].index

df = df[df["Job Title"].isin(valid_jobs)].copy()

print(f"Selected {len(valid_jobs)} job titles dynamically:")
print(valid_jobs.tolist())
print(f"Total samples: {len(df)}")

len(df["Job Title"])

def clean_txt(text: str):
  text = str(text).lower()
  text = re.sub(r'[^a-z0-9\s+#.]',' ',text)
  text = re.sub(r'\s+',' ',text).strip()
  return text
df["clean_des"] = df['Job Description'].apply(clean_txt)

vectorizer = TfidfVectorizer(
    max_features=5000,
    stop_words="english",
    ngram_range=(1, 2),
    min_df=2
)
x = vectorizer.fit_transform(df["clean_des"])
y = df["Job Title"]
model  = LogisticRegression(max_iter=1000,class_weight="balanced")
cv_score = cross_val_score(model,x,y,cv=5,scoring="f1_weighted")
print(cv_score)
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
print(classification_report(y_test,y_pred))

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred, labels=model.classes_)
plt.figure(figsize=(12, 10))
sns.heatmap(cm, annot=True, fmt="d", xticklabels=model.classes_, yticklabels=model.classes_, cmap="Blues")
plt.xticks(rotation=90)
plt.show()

svm_model.fit(x, y) # Ensure model is fitted before prediction

def predict_role_from_skills(skills: list[str]) -> str:
    text = " ".join(skills)
    cleaned = clean_txt(text)
    vector = vectorizer.transform([cleaned])
    return svm_model.predict(vector)[0]

print(predict_role_from_skills(["Python", "Django", "REST API"]))
print(predict_role_from_skills(["JavaScript", "React", "Node.js"]))

random_model =  RandomForestClassifier(class_weight="balanced")
radom_scores = cross_val_score(svm_model, x, y, cv=5, scoring="f1_weighted")
print(f"radom Mean F1: {random_scores.mean():.3f}")
random_model.fit(x, y)
y_pred = model.predict(x_test)
print(classification_report(y_test,y_pred))

knn_model =  KNeighborsClassifier()
knn_scores = cross_val_score(svm_model, x, y, cv=5, scoring="f1_weighted")
print(f"knn Mean F1: {knn_scores.mean():.3f}")
knn_model.fit(x, y)
y_pred = model.predict(x_test)
print(classification_report(y_test,y_pred))

b_model =   BalancedRandomForestClassifier()
b_scores = cross_val_score(svm_model, x, y, cv=5, scoring="f1_weighted")
print(f"b Mean F1: {knn_scores.mean():.3f}")
knn_model.fit(x, y)
y_pred = model.predict(x_test)
print(classification_report(y_test,y_pred))

from sklearn.naive_bayes import MultinomialNB
nb_model = MultinomialNB()
nb_scores = cross_val_score(svm_model, x, y, cv=5)
print(f"nb Mean F1: {nb_scores.mean():.3f}")
nb_model.fit(x, y)
y_pred = model.predict(x_test)
print(classification_report(y_test,y_pred))

ad_model =   AdaBoostClassifier()
ad_scores = cross_val_score(ad_model, x, y, cv=5, scoring="f1_weighted")
print(f"a Mean F1: {knn_scores.mean():.3f}")
ad_model.fit(x, y)
y_pred = model.predict(x_test)
print(classification_report(y_test,y_pred))

from sklearn.svm import LinearSVC
from sklearn.model_selection import cross_val_score

svm_model = LinearSVC(class_weight="balanced", max_iter=2000)
svm_scores = cross_val_score(svm_model, x, y, cv=5, scoring="f1_weighted")
print(f"SVM Mean F1: {svm_scores.mean():.3f}")

# Fit the svm_model on the entire dataset after cross-validation
svm_model.fit(x, y)
y_pred = model.predict(x_test)
print(classification_report(y_test,y_pred))

import joblib
import os

os.makedirs("ml_engine/artifacts", exist_ok=True)
joblib.dump(svm_model, "ml_engine/artifacts/role_model.pkl")
joblib.dump(vectorizer, "ml_engine/artifacts/vectorizer.pkl")

def predict_role(cv_json: dict)  :
    skills = cv_json.get("skills", [])
    if not skills:
        raise ValueError("CV_JSON must contain a non-empty 'skills' list.")

    text = " ".join(skills)
    cleaned = clean_txt(text)
    vector = vectorizer.transform([cleaned])

    predicted_role = svm_model.predict(vector)[0]

    return {
        "predicted_role": predicted_role,
        "skills_used": skills
    }

# تجربة
test_cv = {"skills": ["Python", "Flask", "SQL"]}
print(predict_role(test_cv))